version: '3.8'
services:
  app:
    image: ecommerce-demo-app
    environment:
      - "NEXT_WEBPACK_USEPOLLING=1"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"